export const ENDPOINTS = {
  Auth: {
    Login: "auth/login",
    AddUser: "auth/add-user",
    RefreshToken: "auth/refresh",
    Logout: "auth/logout",
  },
  RoomType: {
    Add: "roomtype/add",
    GetAll: "roomtype/get",
    GetById: "roomtype/get",
    Update: "roomtype/update",
    Delete: "roomtype/delete",
    GetAllWithoutPagination: "roomtype/all"
  },
  Room: {
    Add: "room/add",
    GetAll: "room/get",
    GetById: "room/get",
    Update: "room/update",
    Delete: "room/delete",
    GetByStatus: "room/get-rooms-by-status",
    GetByType: "room/get-by-room-type",
    Search: 'room/search',
  },
  Guest: {
    Add: "guest/add",
    GetAll: "guest/get",
    GetById: "guest/get",
    Update: "guest/update",
    Delete: "guest/delete",
    GetCurrentGuests: 'reservation/get-current-guests',
    Search: "guest/search",
  },
  GroupProfile: {
    AddGroupProfile: "group-profile/add",
    LinkGuestsToGroup: "group-profile/link",
    GetGroupProfiles: "group-profile/get",
    GetGroupProfileById: "group-profile/get",
    DeleteGroupProfile: "group-profile/delete",
    UpdateGroupProfile: "group-profile/update",
    Search: "group-profile/search",
    GetCurrentGroupProfiles: "reservation/get-current-group-profiles",
  },
  RatePlan: {
    Add: "ratePlan/add",
    GetAll: "ratePlan/get",
    GetById: "ratePlan/get",
    Update: "ratePlan/update",
    Delete: "ratePlan/delete",
  },
  Reservations: {
    Add: "reservation/add",
    Update: "reservation/update",
    CheckIn: "reservation/check-in",
    CheckOut: "reservation/check-out",
    Get: "reservation/get-reservation",
    GetId: "reservation/get",
    AddGroupReservation: "reservation/create",
    GetNightPrice: "reservation/get-night-price",
    Cancel: "reservation/cancel",
    GetByGuestId: "reservation/get-reservation-by-guestId",
    CheckedInReservations: "/reservation/get-checked-in-reservations"
  },
  Maintenance: {
    Add: "maintenance/add",
    Start: "maintenance/start",
    Complete: "maintenance/complete",
    GetAll: "maintenance/get",
    GetById: "maintenance/get",
    Update: "maintenance/update",
    Delete: "maintenance/delete",
  },
  Housekeeping: {
    Add: "housekeeping/add",
    Start: "housekeeping/start",
    Complete: "housekeeping/complete",
    GetAll: "housekeeping/get",
    GetById: "housekeeping/get",
    Update: "housekeeping/update",
    Delete: "housekeeping/delete",
  },
  Amenities: {
    GetAllAmenities: "amenity/get",
    Add: "amenity/add",
    GetById: "amenity/get",
    Update: "amenity/update",
    Delete: "amenity/delete",
  },
  Employees: {
    GetAll: "auth/employees",
    GetEmployeeById: "auth/get-user",
    Create: "auth/add-user",
    Search: "auth/employees/search",
    DeleteUpdate: "auth/employee"
  },
  Role: {
    Add: "role/add",
    GetAll: "role/get",
    GetById: "role/get",
    Update: "role/update",
    Delete: "role/delete",
    GetPermissions: "role/get-permissions",
  },
  Currency: {
    GetAddChargeCurrencies: "exchange/exchange-currencies",
    GetExchangeRateCurrencies: "exchange/currencies",
    Convert: "exchange/convert",
  },
  Hotel: {
    Get: "hotel/",
    Update: "hotel/update",
  },
  Area: {
    Add: "area/add",
    GetAll: "area/get",
    GetById: "area/get",
    Update: "area/update",
    Delete: "area/delete",
  },
  Folio: {
    AddCharge: "folio-item/add-charge",
    UnsettledCharges: "folio-item/unsettled-charges",
    AddPayment: "folio-item/settle",
    ViewPayment: "folio-item/get-handled-folio-items",
    VoidPayments: "folio-item/void",
    SettleLateCheckoutFee: "folio-item/settle-late-checkout",
    GetLateCheckoutFee: "folio-item/late-checkout-fee",
    TransferCharge: "folio-item/transfer",
    GetTransferItems: "folio-item/all-items"
  },
  ExchangeRate: {
    Get: "exchange/get",
    GetById: "exchange/get",
    Add: "exchange/add",
    Update: "exchange/update"
  },
  Departments: {
    Manage: "hotel/department"
  }
};
